### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by Raul824** [JustAMan/vp9ify#1]
Hello JustAMan

I am getting below error while try to use recoding could you let me know if i am using it correctly or is there an issue in the command which i am using.
```
python3 main.py Angrezi_medium.mkv --dest /tmp
2020-04-10 10:35:14,296|INFO|Found 1 items
Traceback (most recent call last):
  File "/main.py", line 185, in <module>
    main()
  File "/main.py", line 128, in main
    entry = parse_fentry(fentry, suffix, forced_parser, forced_params)
  File "/main.py", line 35, in parse_fentry
    entry = parser.parse(fname, fpath)
  File "/recode/media/movie.py", line 42, in parse
    return cls(fpath, fname)
  File "/recode/media/movie.py", line 16, in __init__
    self.prefix = ''.join('%02x' % ord(ch) for ch in hashlib.sha256(name).digest()[:2])
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by JustAMan** [comment]
Oh, bugs surfacing after my untested migration to Python3...
Will look soon. Thanks for using! :)

**Comment by Raul824** [comment]
It got fixed by adding the encode in ./recode/media/movie.py

self.prefix = ''.join('%02x' % ord(ch) for ch in hashlib.sha256(name.encode('utf-8')).digest()[:2])

But now 2nd issue.

TypeError: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'

**Comment by JustAMan** [comment]
Yeah, untested rewrites aren't always ending well... :) Sorry about that. I'll try to fix it soon(tm).

**Comment by JustAMan** [comment]
@Raul824 please test 9352534fbb1e29c204495f5f20a53ba17a44a3bc (pushed to `master`), I've fixed a few Python3 issues.
